### ISSUE TITLE
cant seem to press the loginbutton

### ISSUE THREAD

**Issue by Smeagol001** [currency-cop/currency-cop#39] opened 2018-04-25 11:46 UTC
using win10 x64  and cc 2.0.0 beta4  when i want to login clicking the button seems to not do anything atall

**Comment by MediEvilHero** [comment] 2018-04-25 15:55
Did you paste your POE Session ID into the field first?

**Comment by Smeagol001** [comment] 2018-04-25 18:57
yeah i did but nothings happening



2018-04-25 17:55 GMT+02:00 MediEvilHero <notifications@github.com>:

**Comment by Smeagol001** [comment] 2018-04-25 19:49
if i puit nothing in i get an error bit if i paste thjhe id in  thers just
nothing happening at lall

2018-04-25 20:57 GMT+02:00 Smea Gol <mkratina@gmail.com>:

**Comment by nijikokun** [comment] 2018-05-01 03:15
Interesting, if you are on discord could you send me your logs?

They live in the `%appdir%/currency-cop` folder

**Comment by Smeagol001** [comment] 2018-05-01 07:34
what server?


2018-05-01 5:15 GMT+02:00 Nijiko Yonskai <notifications@github.com>:

**Comment by Smeagol001** [comment] 2018-05-01 07:43
now that you mentioned the logfile i looked into it and it said expired
sesion id  you probbably should ad dan errror essage for that into the
screen so ppl know that maybe their llogin expired on the poe site
otherwise it looks like the thing isnt working

2018-05-01 9:34 GMT+02:00 Smea Gol <mkratina@gmail.com>:

**Comment by WilliamElder** [comment] 2018-05-03 07:18
I can confirm that the issue only occurs when the session ID is invalid/expired. The issue is fixed by logging in again on the Path of Exile forum. 

Path of Exile's cookies aren't auto-removed when expired on some browsers, so some users (including myself) probably tried to use an expired one without realizing it. Some visual feedback (e.g. invalid session id, try logging out and logging in again) would be much appreciated.

Keep in mind that you explicitly have to log in to the forum for the cookie to be refreshed; just visiting  https://www.pathofexile.com/ without being logged in doesn't fix it. I wasn't able to see whether or not the session ID has to be refreshed manually if already logged in by relogging, but I would assume that it is handled by the website automatically.

Though now we have a new problem- currency cop doesn't handle the pending Flashback Event (BRE001) correctly, but I will open that in a new issue.

**Comment by nijikokun** [comment] 2018-05-03 07:19
I see, in fact, it should give back a visual cue, I can look into fixing that 💯

**Closed as completed** 2018-06-29 03:01 UTC
